INSERT INTO dbo.Events
	(Name, Presenter, Date, Duration, Location, Description)
VALUES
	('Event 1',
	 'Person 1',
	 GETUTCDATE(),
	 8,
	 'Somewhere, USA',
	 'This is the description of Event 1'),
	 ('Event 2',
	 'Person 2',
	 GETUTCDATE(),
	 8,
	 'Somewhere, USA',
	 'This is the description of Event 2'),
	 ('Event 3',
	 'Person 3',
	 GETUTCDATE(),
	 8,
	 'Somewhere, USA',
	 'This is the description of Event 3'),
	 ('Event 4',
	 'Person 4',
	 GETUTCDATE(),
	 8,
	 'Somewhere, USA',
	 'This is the description of Event 4'),
	 ('Event 5',
	 'Person 5',
	 GETUTCDATE(),
	 8,
	 'Somewhere, USA',
	 'This is the description of Event 5');